### ISSUE TITLE
Issues with shortcuts and french keyboard

### ISSUE THREAD

**Issue by olvlvl** [emmetio/emmet-eclipse#10]
Hello,

The `Ctrl+Alt+[` and the `Ctrl+Alt+]` shortcuts used to jump to the previous and next edit points are impossible to use with a French keyboard because "(" and "[" are on the same key and we actually enter `Ctrl+Alt+(` to produce "[" and `Ctrl+Alt+)` to produce "]". So when I enter `Ctrl+Alt+(` to produce "[" I end up on the previous edit point.

I unbound the shortcuts but it was really confusing.

Could you include a notice, disable the shortcuts or use different ones ?
##

**Comment by cdutaret** [comment]
As a side effect, in some editors like the JSDT editor, typing `[` results in the previous edit point action, and makes it impossible to actually type `[`

**Comment by aquachris** [comment]
Ok, if anyone else is looking to work around this issue by removing the keyboard shortcut, here's how to do it: In Eclipse, go to "Window" -> "Preferences", then "General" -> "Keys". Sort the list using the column "Category" and scroll down until you find the category "Emmet". 

The shortcuts for "Select Next Item" and "Select Previous Item" are what causes the issue with `[` and `]`. Use the button "Unbind Command" to remove those shortcuts.

Hope this helps :)
