### ISSUE TITLE
Square brackets

### ISSUE THREAD

**Issue by kmaric** [emmetio/emmet-eclipse#32]
I discovered some issues with square brackets after updating to newer version.
After i click ALTGr + F or G which is only way I can type square brackets " [ & ] "
on my (Croatian keyboard) keyboard I have some search and some other stuff apearing.

On version 1.0 it all worked fine. :(

Any solutions?

**Comment by aquachris** [comment]
Having the same problem with a German keyboard (using AltGr+8 and AltGr+9). Is there a solution or workaround for this?
