### ISSUE TITLE
Provide eclipse plugin as downloadable package

### ISSUE THREAD

**Issue by gsnerf** [emmetio/emmet-eclipse#48]
Hi there, is it possible to provide a downloadable package that can be extracted to the dropins folder?

Background: many larger companies pipe internet access through a proxy and filter access to websites on a per application basis. The company I currently work for blocks access for eclipse to all websites except the official eclipse udpate sites, so I currently can't use the plugin which is a shame :(

**Comment by sergeche** [comment]
Hi, just created release with plugin binary, hope it helps: https://github.com/emmetio/emmet-eclipse/releases/tag/v1.0

**Comment by gsnerf** [comment]
Works like a charm. Thank you very much!
