### ISSUE TITLE
Remove control+d shortcut

### ISSUE THREAD

**Issue by chuchiperriman** [emmetio/emmet-eclipse#5]
It is the default delete line shortcut and we use it all the time. If you add the same shortcut then eclipse propose delete line or Match Pair Tag instead of delete the line directly.

Please, do the shortcut configurable, or change it or remove it

**Comment by jabby** [comment]
Any chance to change the default shortcut ? It's really annoying. 

I changed my configuration, but I think it's not a good idea to use the ctrl+d shortcut which is one of the most use shortcut in Eclipse.
