### ISSUE TITLE
Exception while installing the plugin in Eclipse

### ISSUE THREAD

**Issue by GGSvennson** [emmetio/emmet-eclipse#51]
Hi,

I am trying to install the Emmet plugin in my Eclipse IDE PHP Luna following the instructions that are provided to that effect,

1.- Go to Help> Install New Software ... in your Eclipse IDE
2.- Add http://emmet.io/eclipse/updates/ in update sites
3.- Check Emmet for Eclipse group in available plugins list, click Next button and follow the installation instructions
4.- Restart Eclipse

But I always get the same exception,

Unable to read repository at http://emmet.io/eclipse/updates/content.xml.
Unable to read repository at http://emmet.io/eclipse/updates/content.xml.
Hostname in certificate did not match: <emmet.io>! = <Docs.emmet.io> OR <docs.emmet.io>

Any idea or suggestion to solve this issue?

**Comment by sergeche** [comment]
Try to use either http://download.emmet.io/eclipse/updates/ or https://emmet.io/eclipse/updates/

**Comment by GGSvennson** [comment]
Hi Sergey


Using http://download.emmet.io/eclipse/updates/ is ok.


Thanks a lot,

Jose


________________________________
De: Sergey Chikuyonok <notifications@github.com>
Enviado: viernes, 7 de abril de 2017 9:14
Para: emmetio/emmet-eclipse
Cc: Jose Alvarez de Lara; Author
Asunto: Re: [emmetio/emmet-eclipse] Exception while installing the plugin in Eclipse (#51)


Try to use either http://download.emmet.io/eclipse/updates/ or https://emmet.io/eclipse/updates/
